
eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true 
     
server:
   port: 8902
spring:
   application:
      name: service-feign
feign:
  httpclient:
    enabled: true
turbine:
     appConfig: service-feign, service-ribbon
     aggregator:
         clusterConfig: default
     clusterNameExpression: new String("default")