
eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true 
     
server:
   port: 8911
spring:
   application:
      name: service-feign2
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
  httpclient:
    enabled: true

  